version: '2'
services:
  nginx:
    build:
      context: ./nginx_docker
      dockerfile: ./Dockerfile
    ports:
      - 8080:80
    depends_on:
      - web
    links:
      - web
  web:
    build: .
    ports:
      - 3000:3000
